import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { Bebas_Neue } from "next/font/google";
import "./globals.css";
import { DM_Mono } from "next/font/google";
import { Sofia_Sans_Condensed } from "next/font/google";
import { Spline_Sans_Mono } from "next/font/google";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

const SofiaSansCondensed = Sofia_Sans_Condensed({
  variable: "--font-Sofia-Sans-Condensed",
  subsets: ["latin"],
    weight: "800",
})

const SplineSansMono = Spline_Sans_Mono({
  variable: "--font-Spline-Sans-Mono",
  subsets: ["latin"],
  weight: "400"
})

const bebasNeue = Bebas_Neue({
  variable: "--font-bebas-neue",
  subsets: ["latin"],
  weight: "400",
});

const dmMono = DM_Mono({
  variable: "--font-dm-mono",
  subsets: ["latin"],
  weight: ["400"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${dmMono.variable} ${bebasNeue.variable} ${SofiaSansCondensed.variable} ${SplineSansMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
