import type { Metadata } from "next";
import "./globals.css";
import localFont from "next/font/local";
import { Playfair_Display } from "next/font/google";
import { Kameron } from "next/font/google";
import { Gasoek_One } from "next/font/google";

const playfairDisplay = Playfair_Display({
    subsets: ["latin"],
    weight: ["400", "500", "600", "700", "800", "900"],
    variable: "--font-playfair-display",
})
const kameron = Kameron({
    subsets: ["latin"],
    weight: ["400", "500", "600", "700"],
    variable: "--font-kameron",
})
const gasoekOne = Gasoek_One({
    subsets: ["latin"],
    weight: ["400"],
    variable: "--font-gasoek-one",
})

const satoshi = localFont({
  src: [
    {
      path: "../public/fonts/Satoshi-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../public/fonts/Satoshi-LightItalic.otf",
      weight: "300",
      style: "italic",
    },
    {
      path: "../public/fonts/Satoshi-Regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../public/fonts/Satoshi-Italic.otf",
      weight: "400",
      style: "italic",
    },
    {
      path: "../public/fonts/Satoshi-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../public/fonts/Satoshi-MediumItalic.otf",
      weight: "500",
      style: "italic",
    },
    {
      path: "../public/fonts/Satoshi-Bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../public/fonts/Satoshi-BoldItalic.otf",
      weight: "700",
      style: "italic",
    },
    {
      path: "../public/fonts/Satoshi-Black.otf",
      weight: "900",
      style: "normal",
    },
    {
      path: "../public/fonts/Satoshi-BlackItalic.otf",
      weight: "900",
      style: "italic",
    },
  ],
  variable: "--font-satoshi",
});

const BespokeSans = localFont({
    src: "../public/fonts/BespokeSans-Regular.otf",
    weight: "700",
    style: "normal",



    variable: "--font-bespoke-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import { Preloader } from "@/components/Preloader";

// ... existing imports

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={` ${satoshi.variable} ${BespokeSans.variable} ${playfairDisplay.variable} ${gasoekOne.variable} ${kameron.variable} antialiased bg-[#EFEFEF]`}
      >
        <Preloader />
        {children}
      </body>
    </html>
  );
}
